apiVersion: v1
kind: Service
metadata:
  name: my-service
  labels:
    app: smart-store
spec:
  type: NodePort
  selector:
    app: smart-store
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
