apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: smart-store
spec:
  ingressClassName: nginx
  rules:
  - host: smart-store.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: smart-store
            port:
              number: 80
              